### ISSUE TITLE
Issues with origin (intern_dist)

### ISSUE THREAD

**Issue by lickx** [lickx/opencollar-os#25]
**Problem 1**

The default, in oc_settings.lsl, line 403:
if (llGetNumberOfPrims()>5) g_lSettings = ["intern_dist",(string)llGetObjectDetails(llGetLinkKey(1),[27])];

This line gets the avatar key that is the last owner of the root prim. However, last owner will simply change to yourself on attached items on the 2nd time you attach it. This is the usual behaviour in OpenSim and SL.

I'm thinking of changing it to:

if (llGetNumberOfPrims()>5) g_lSettings = ["intern_dist",(string)llGetObjectDetails(llGetLinkKey(llGetNumberOfPrims()),[OBJECT_CREATOR])];

Pros: Creator of the last link will be used, which will be the collar artwork (the first 5 links might be re-used core prims from a standard collar, having us as creator)
Cons: The collar creator might've used 3rd party fullperm sculpties/meshes and in that case the intern_dist key would equal the creator of that 3rd party prim.

**Problem 2**

This is a hypergrid related problem with clickable URI's in oc_root.lsl. Hypergrid makes things so much more complicated since hypergrid avi keys are not known to the local grid and can't resolve.

So we have the UUID of the origin but don't know their homegrid. The grid they're on could be local, which would work fine with a secondlife:// inspect; or could be remote on the hypergrid, which only works IF we know the grid URL (say hg.osgrid.org:80), AND use hop:// instead of secondlife://. Otherwise it will resolve to a blank profile with string '(Loading...)'.

So I suggest checking if llKey2Name(kAvi) resolves to a non-empty string, then return a clickable URI, and if empty, kAvi is from the hypergrid so just put 'Hypergrid'

**Comment by WendyStarfall** [comment]
In my experience (on Second Life®) the origin stays persistent until you rez the item to the ground, and reset the scripts manually. This feature was really implemented because we have that vast amount of other parties on our grid, and also many collars are hand made and passed from avatar to avatar.

It's nice to be able to determine where an item came from. You'd really need the merchant's or "distributor's" help more often than the creator's. I'm not sure how all that is handled in the Hypergrid space. I always imagine that there, people are more patient, inclusive, happier, kinder.. (don't ruin my fantasy just yet! 🙊 ) 

Okay, I'm really meaning to say that the new ``oc_root`` could simply have a bunch of global strings that each merchant and/or creator can fill out. Then it is their's, their brand, their name, their links and slurls, and still compatible with the rest. ``oc_root`` would have to be issued differently than the normal update package, and updates would have to be configured in a way to not to override ``oc_root``.  If there are worries that some people might fake origin for whatever reason, it's no issue to set ``oc_root`` to be non modifiable as long as others can easily find the source. You couldn't have done that with ``oc_sys`` because of the old licensing.

I hope that some of this was useful to you.

**Comment by lickx** [comment]
Thank you for your input, I can do something with this info.

In SL (and OpenSim), OBJECT_LAST_OWNER_ID changes to the current object owner at the 2nd attach and afterwards (only on the initial/1st attach it shows the real previous owner). I might be able to store the real origin on first rez but it would be very hacky and it would only be the avi UUID only not the grid origin.

When a grid URL is known, a inspect floater can be shown using hop://<gridname>:<port>/app/agent/<uuid>/inspect and this will work with most modern viewers like Firestorm very similar to the secondlife:// links. I think the trouble is there is no way to get the origin grid with GetObjectDetails, only the avi UUID.

The info on oc_root is helpful. I'm going to rewrite it so dist takes the form 'Firstname.Lastname @gridurl:port' and that could be converted into a hop:// address. Then probably leave out the line that sets it in oc_settings. I just didn't know collar creators where supposed to touch the oc_root script or that it could be excluded in the patcher.

Also.. the origin/distributor vs creator is confusing :) I think in OpenSim end-users will want to contact the creator at first, and else resort to an inworld collar related group.
